routes:
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account

collections:
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: 'tag:hash-en'
  /fr/:
    permalink: /fr/{slug}/
    template: index-fr
    filter: 'tag:hash-fr'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
