routes:
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account

collections:
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: 'tag:hash-en'
  /fr/:
    permalink: /fr/{slug}/
    template: index-fr
    filter: 'tag:hash-fr'
  /ko/:
    permalink: /ko/{slug}/
    template: index-ko
    filter: 'tag:hash-ko'
  /chi/:
    permalink: /chi/{slug}/
    template: index-chi
    filter: 'tag:hash-chi'
  /jpn/:
    permalink: /jpn/{slug}/
    template: index-jpn
    filter: 'tag:hash-jpn'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
