routes:
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[hash-cn,hash-jp,hash-kr]'
  /kr/:
    permalink: /kr/{slug}/
    template: index-kr
    filter: 'tag:hash-kr'
  /cn/:
    permalink: /cn/{slug}/
    template: index-cn
    filter: 'tag:hash-cn'
  /jp/:
    permalink: /jp/{slug}/
    template: index-jp
    filter: 'tag:hash-jp'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
